apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-14 - 15:21:12 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: logging-service
  name: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: logging-service
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-14 - 15:21:12 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: logging-service
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: sbsip-jenkins.convergens.dk:18444/logging-service:1.0.0
        imagePullPolicy: Always
        name: logging-service
        ports:
        - containerPort: 8095
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-14 - 15:21:12 +0000
  labels:
    app.kubernetes.io/name: logging-service
    app.kubernetes.io/version: 1.0.0
  name: logging-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8095
  selector:
    app.kubernetes.io/name: logging-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
