apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-28 - 11:44:47 +0000
  labels:
    app.kubernetes.io/version: 1.0.1
    app.kubernetes.io/name: case-delivery-service
  name: case-delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.1
      app.kubernetes.io/name: case-delivery-service
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-04-28 - 11:44:47 +0000
      labels:
        app.kubernetes.io/version: 1.0.1
        app.kubernetes.io/name: case-delivery-service
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/case-delivery-service:1.0.1
        imagePullPolicy: Always
        name: case-delivery-service
        ports:
        - containerPort: 8092
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-28 - 11:44:47 +0000
  labels:
    app.kubernetes.io/name: case-delivery-service
    app.kubernetes.io/version: 1.0.1
  name: case-delivery-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8092
  selector:
    app.kubernetes.io/name: case-delivery-service
    app.kubernetes.io/version: 1.0.1
  type: ClusterIP
