apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-31 - 09:02:51 +0000
  labels:
    app.kubernetes.io/version: 1.0.4
    app.kubernetes.io/name: soap-service
  name: soap-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.4
      app.kubernetes.io/name: soap-service
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-31 - 09:02:51 +0000
      labels:
        app.kubernetes.io/version: 1.0.4
        app.kubernetes.io/name: soap-service
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/soap-service:1.0.4
        imagePullPolicy: Always
        name: soap-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      serviceAccountName: soap-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-31 - 09:02:51 +0000
  labels:
    app.kubernetes.io/name: soap-service
    app.kubernetes.io/version: 1.0.4
  name: soap-service
spec:
  ports:
  - name: http
    nodePort: 32001
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: soap-service
    app.kubernetes.io/version: 1.0.4
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-31 - 09:02:51 +0000
  labels:
    app.kubernetes.io/version: 1.0.4
    app.kubernetes.io/name: soap-service
  name: soap-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: soap-service-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: soap-service
