argo-cd:
  dex:
    enabled: false
  service:
    type: NodePort
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
