apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prak
  namespace: carejova
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - praktwo.digitor.dk
    secretName: quickstart-example-tls
  rules:
    - host: praktwo.digitor.dk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: quarkus-pipeline-test
              port:
                number: 80
