apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-28 - 12:34:21 +0000
  labels:
    app.kubernetes.io/name: message-validator-service
    app.kubernetes.io/version: 1.0.5
  name: message-validator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: message-validator-service
      app.kubernetes.io/version: 1.0.5
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-04-28 - 12:34:21 +0000
      labels:
        app.kubernetes.io/name: message-validator-service
        app.kubernetes.io/version: 1.0.5
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/message-validator-service:1.0.5
        imagePullPolicy: Always
        name: message-validator-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-28 - 12:34:21 +0000
  labels:
    app.kubernetes.io/name: message-validator-service
    app.kubernetes.io/version: 1.0.5
  name: message-validator-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: message-validator-service
    app.kubernetes.io/version: 1.0.5
  type: ClusterIP
