apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-29 - 11:53:05 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: file-validator-service
  name: file-validator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: file-validator-service
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-29 - 11:53:05 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: file-validator-service
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/file-validator-service:1.0.0
        imagePullPolicy: Always
        name: file-validator-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-29 - 11:53:05 +0000
  labels:
    app.kubernetes.io/name: file-validator-service
    app.kubernetes.io/version: 1.0.0
  name: file-validator-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: file-validator-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
